[settings]
camera_index = 0
picture_path = Pictures
mode = image
run_mode = CONSOLE
fontscale = 0.75
thickness = 1
text_color = (0,0,0)
font = FONT_HERSHEY_COMPLEX_SMALL
target_width = 640

[pattern_recognition]
# Define HSV ranges
lower_red1 = [0, 70, 50]
upper_red1 = [10, 255, 255]
lower_red2 = [170, 120, 70]
upper_red2 = [180, 255, 255]
lower_green = [25, 52, 72]
upper_green = [102, 255, 255]
lower_blue = [94, 120, 120]
upper_blue = [120, 255, 255]
lower_yellow = [15, 150, 20]
upper_yellow = [35, 255, 255]
lower_purple = [130, 100, 100]
upper_purple = [160, 255, 255]

[logging]
path = Output/log.csv